export { HomePage } from './HomePage';
export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { ProductCategoryPage } from './ProductCategoryPage';
export { SkincareCategory } from './SkincareCategory';
export { MakeupCategory } from './MakeupCategory';
export { BodycareCategory } from './BodycareCategory';
export { FragranceCategory } from './FragranceCategory';
export { ProductDetailPage } from './ProductDetailPage';