spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.micoz: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
